name: financialservicesapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  hive_flutter: ^1.1.0
  url_launcher: ^6.2.5
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.1.1
  http:
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.3
  build_runner: ^2.3.3
  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
    - assets/images/



